# file containing the configuration for several tools used
# THIS FILE MUST NOT BE CHANGED

[tool.black]
line-length = 80

[tool.isort]
profile = "black"
line_length = 80
src_paths = "."
skip_gitignore = true
